### ISSUE TITLE
[question] Ideas on adding of new passwords to database

### ISSUE THREAD

**Issue by royvs33** [LEDfan/keywi#107]
First of all I would like to say that I have read your goals, and no editing of the Keepass database.
What would your opinion be of a feature that prompts to add credentials to the database when a user creates a new account or logs in to a account that is not yet in the database.

**Comment by Rictusempra** [comment]
I doubt if Mozilla has added such API yet

**Comment by LEDfan** [comment]
Hi @royvs33, thanks for you interest.

Currently my opinion is still that Keywi should not add credentials to the Keepass database. Especially since most passwords should be generated using Keepass to guarantee safe passwords.

I'll close this, but will reopen when we reconsider this.
