### ISSUE TITLE
Not able to autofill anymore

### ISSUE THREAD

**Issue by TheCodesterr** [LEDfan/keywi#116]
I'll open KeePassXC and enter the password to connect Keywi to the database, but when I attempt to autofill, it does not work. 

I went to the add-on's settings within Firefox and verified that Secure Storage Unlocked is true and Keypass Database Associated is true.

Do you know why this is happening?

**Comment by LEDfan** [comment]
Thanks for you bug report!

For me filling still works, however, I found a bug with filling when the Secure Storage isn't unlocked so maybe this is the bug you are experiencing. (Not sure if you looked at the addon settings before or after trying filling)

The bug fix can be tested in #117, which contains a pre-release.

Please let us know if this solves your bug. Thanks.

**Comment by TheCodesterr** [comment]
Thanks for your reply. Not sure what was going on, but it wasn't working for me for a few days. Seems to be working again. 

Not sure if I should create another issue for this, but auto filling Amazon's website seems to not work.

**Comment by RobinJadoul** [comment]
If it's broken, it's worth an issue.
We've had some problems with specific sites before (Microsoft), so it's not impossible.

**Comment by RobinJadoul** [comment]
Fixed in #117
