### ISSUE TITLE
Prepare Release

### ISSUE THREAD

**Issue by LEDfan** [LEDfan/keywi#53]
TODO:
  - [x] README
    - [x] installation
    - [x] usage
    - [x] authors
    - [x] screenshots
    - [x] minimum FF version
    - [x] advise to disable of firefox keeping tracks of logins
   - [x] license
 - [x] setup license
 - [x] manifest
 - [x] min version
 - [x] name for this project

**Comment by LEDfan** [comment]
We have a name now "Keywi"

**Comment by LEDfan** [comment]
Almost fixed by #54 
TODO:
 - [ ] read and check README @LEDfan

**Comment by RobinJadoul** [comment]
Initial release done, closing
