### ISSUE TITLE
Suggestion: option not to prompt to unlock storage when firefox is started

### ISSUE THREAD

**Issue by ak168421** [LEDfan/keywi#56]
Currently, whenever Firefox is started, keywi opens a popup to ask for a password to unlock the secure storage. However, most of the times I open firefox I don't need to enter a password. It would be nice if there was an option not to show this popup at startup, and only show it when a password is entered using the right click menu or keyboard shortcut.

Thanks for this add-on, it has been a great improvement over the previous ones I have used.

**Comment by LEDfan** [comment]
Thanks for this suggestion this is implemented in v0.1.0-beta3 (#57) you can download it here: https://github.com/LEDfan/keywi/releases/tag/v0.1.0-beta3
