### ISSUE TITLE
locale support

### ISSUE THREAD

**Issue by Rictusempra** [LEDfan/keywi#58]
I'd love to help out with zh-CN locale but can't find any guideline.
How should I proceed

**Comment by Rictusempra** [comment]
@LEDfan I'm now adding zb-CN locale. Just to confirm, in `messages.json` , it should be done simply with `message`. There is no need to translate `description`. Am I right?

**Comment by LEDfan** [comment]
@Rictusempra correct, the description is a description for translators.

**Comment by LEDfan** [comment]
Fixed by #62
