### ISSUE TITLE
Not compitable with Tab Mix Plus session manager

### ISSUE THREAD

**Issue by Rictusempra** [LEDfan/keywi#59]
environ.: FF 54 beta, Kewi 0.1.0beta2, TMP 0.5.0.4pre.170525a1

STR:
1. Install TMP, enable Tab Mix Plus session manager and disable that built within FF
2. set TMP preferences linke this:
![default](https://user-images.githubusercontent.com/16912240/27009226-72ffac20-4ebb-11e7-83e4-b27b208de54a.png)

Also enable Single Window Mode on Link tab.

When Keywi pops up a window requiring password on restarting FF, TMP will also ask if you are to restore session.

Click yes here.

Actual Results: Sorry that I don't know how to descibe that, the session seems to be drop into a wrong window?

**Comment by RobinJadoul** [comment]
I would advise to install one of the later beta's available here on github (https://github.com/LEDfan/keywi/releases, not yet released/approved on AMO) and enabling the `Don't unlock the secure storage on startup` option that way, keywi won't prompt you on startup but on first usage, circumventing the issue.

I'm not sure everything will work completely fine when the popups are in separate tabs (such as those tabs not closing when submitting/cancelling), but the basic functionality should be usable like that.

**Comment by RobinJadoul** [comment]
@Rictusempra is this still a the case? The behaviour may have changed a bit with #92

**Comment by Rictusempra** [comment]
Well, since I am on Quantum already I have no chance to test this easily.
But I think leaving this until tab mix plus WebExtension will be more proper since it is still legacy
