### ISSUE TITLE
[feature request] fill username only

### ISSUE THREAD

**Issue by EMLVIRUS** [LEDfan/keywi#61]
helpful on specific occasions for fields step by step, e.g. outlook/google loginning

**Comment by RobinJadoul** [comment]
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd> Will fill just the username field when there is no password field to be found

**Comment by EMLVIRUS** [comment]
Maybe I need to put this more clearly: add this to the context menu

**Comment by EMLVIRUS** [comment]
Sorry, this seems kinda misunderstanding..................
