### ISSUE TITLE
Does not work with KeePassXC

### ISSUE THREAD

**Issue by noahadvs** [LEDfan/keywi#64]
KeePassXC supports KeePassHTTP, but Keywi doesn't seem to recognize it.
When I enter a password for the Keywi setup, this happens:
http://i.imgur.com/DfDQ8Hb.png

KeePassXC seems to be listening to the correct port.
http://i.imgur.com/lQ2PbXO.png

**Comment by RobinJadoul** [comment]
Weird, it works for me...
The database and KeepassHTTP were running when you tried the startup?
Can you try filling a password somewhere, that should trigger a new attempt to associate with the database

**Comment by noahadvs** [comment]
Yes, those 2 things were up and running when I tried to use Keywi, but it seems to be a problem on my end because this addon, which used to work, doesn't work either: https://addons.mozilla.org/en-US/firefox/addon/keepasshelper/
