### ISSUE TITLE
Minor appearance bug

### ISSUE THREAD

**Issue by Rictusempra** [LEDfan/keywi#88]
![image](https://user-images.githubusercontent.com/16912240/32652489-656aaa50-c63f-11e7-925a-e4fbbfce151a.png)

This occurs if you close window before you unlock Secure Storage as soon as it pops up (you have properly set up association before).

**Comment by RobinJadoul** [comment]
Could you please elaborate what the actual problem and the steps to reproduce it are?

**Comment by Rictusempra** [comment]
@RobinJadoul the black edge isn't supposed to be there.

Str: 
1. install Firefox and keywi
1. Set up association properly
1. Restart browser
1. Close the window where you unlock Secure Storage

**Comment by LEDfan** [comment]
We aren't able to reproduce this, it could be caused by some specific desktop environments. Can you specify which OS, version, desktop environment and FF version you are running? Thanks!

**Comment by Rictusempra** [comment]
FIrefox 58.0b5 on Windows Pro 10.16299.64.
Be sure you uncheck `Don't unlock the Secure Storage at start up` and close the Keywi window as soon as it pops up.
And plus, if it ever occurs, clicking on it will recall the Keywi window.
So it seems not be simply about appearance.

**Comment by RobinJadoul** [comment]
This feels more like a Firefox bug than really related to Keywi.
Given that you're on a Firebox Beta, it might be better to try and reproduce this with another kind of window (perhaps) and reporting it to mozilla.
