### ISSUE TITLE
Display acceptable characters for password used by Secure Storage

### ISSUE THREAD

**Issue by Rictusempra** [LEDfan/keywi#91]
This is my default generating method in KeePass
![image](https://user-images.githubusercontent.com/16912240/32936547-aa9a476e-cbaf-11e7-9e86-0cccf8ba080c.png)
I spend a chunk of time to adjust the method to generate one for Keywi

**Comment by LEDfan** [comment]
The only place where this password is directly used is here: https://github.com/LEDfan/keywi/blob/master/background/Crypto.js#L86 where it's directly passed to the brower's Crypto API. According to the docs I can't find any limit on the given key, and unfortunately I can't reproduce the issue. I tried with 
```
Fzt|IX/QJdo10jeN5sXa\.|ja,)?]IVl<=Jg>oZ#Xj\`nZfVCT/~o\ ?VqQ1aWL\"yJN7|z9DL!D5cR{|N:N@OPOc-Cp;XU#B;L.~
```

Which Keepass program are you using (Keepass, KeepassXC) and which version? It is maybe possible to provide a failing password (of course one you **don't** use! :smiley:)

**Comment by Rictusempra** [comment]
Strange.
I can still reproduce it at the previous version but not now.
I am closing this now and reopen whenever I encounter this again.
Sorry for my interrupting.
