### ISSUE TITLE
Another MS Filling Failure

### ISSUE THREAD

**Issue by Rictusempra** [LEDfan/keywi#96]
https://portal.office.com
redirected to
https://login.microsoftonline.com
But
login.live.com is indeed  working
Weird....

**Comment by RobinJadoul** [comment]
Not so weird actually, since the workaround was specifically for the login.live.com url, because any other fix would break too many other sites.
On the other hand, it shouldn't be too much work to extend this fix to other domains

**Comment by Rictusempra** [comment]
There is a lazy fix:
add option to allow context manual everywhere.
Since users have to click them manually and KeePassHTTP will also prompt up confirmation dialog.
So I believe there won't be too much issue.
